### ISSUE TITLE
New maintainer for Realme 7 Pro

### ISSUE THREAD

**Issue by BalayBera** [RisingOSS-devices/official#15]
## Device you want to apply for
```
Realme 7 Pro (RMX2170)
```

## Device tree sources

```
https://github.com/BalayBera/rising_device_realme_RMX2170
https://github.com/BalayBera/kernel_realme_sm7125
https://gitlab.com/BalayBera/vendor_realme_RMX2170
```

## Link to the platform where you have released your unofficial build
```
https://t.me/realme7ProUpdates
```

## Other ROM's you maintain officially or unofficially
```
Maintain Pixel Extended unofficially
```

## Bugs on unofficial build
```
Screen flickering starts when using the camera or playing videos (where the GPU is being used) and then suddenly some external event happens, such as a notification pop-up or volume change, etc. 
```

## How long have you been building for?
```
Almost one year
```

## SELinux status?
```
Enforcing
```

## Are you using a prebuilt kernel? If yes, why?
```
No
```

### Telegram username
```
BalayBera
```

**Comment by risingtechopensourcesoftware** [comment]
Hello,

Thank you for your interest in becoming a maintainer for RisingOS. Your application is currently marked as "Needs Resolution" or "Improvements" due to a critical issue on your side that must be addressed before our team can proceed with a full review.

🛠️ Please take the necessary steps to resolve the critical issue outlined in your application. Once resolved, our team will resume the review process.

⚠️ To keep up with your maintainership updates, please keep this issue open. In case of a change of mind, feel free to close this issue; however, inactivity will also result in this issue being closed.

🤖 Notice: This message is auto-generated. For any questions or assistance, please contact us at [risingtechossofficial@gmail.com].

Best regards,
[Rising Tech Open Source Software]

**Comment by BalayBera** [comment]
Thank you for your response. I'm eager to address the critical issue you've highlighted for the official maintainership of Rising OS. Could you please specify if the critical issue is related to the screen flickering problem on the device, or if it concerns improvements required in my device tree or any other specific aspect? Clarity on this matter will help me focus on the necessary enhancements for the official approval. Thank you for your guidance.
