### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Pandaispro** [RisingOSS-devices/official#16]
## Device you want to apply for

```

Samsung Galaxy A70 (a70q)

```

## Device tree sources

```

https://github.com/Pandaispro/android_device_samsung_a70q

https://github.com/Pandaispro/android_kernel_samsung_sm6150

https://github.com/Pandaispro/android_kernel_samsung_sm6150

```

## Link to the platform where you have released your unofficial build
```
(https://t.me/Pandasromupdates/26)



```

## Other ROM's you maintain officially or unofficially
```
Insert here
Derp Fest
Bliss 
Alpha Droid
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
A Year
```

## SELinux status?
```
Permissive.
```

## Are you using a prebuilt kernel? If yes, why?

```
No.
```

### Telegram username
```
DynamicPanda11
```

**Comment by risingtechopensourcesoftware** [comment]
Hello,

Thank you for your interest in becoming a maintainer for RisingOS. Your application is currently marked as "Needs Resolution" or "Improvements" due to a critical issue on your side that must be addressed before our team can proceed with a full review.

🛠️ Please take the necessary steps to resolve the critical issue outlined in your application. Once resolved, our team will resume the review process.

⚠️ To keep up with your maintainership updates, please keep this issue open. In case of a change of mind, feel free to close this issue; however, inactivity will also result in this issue being closed.

🤖 Notice: This message is auto-generated. For any questions or assistance, please contact us at [risingtechossofficial@gmail.com].

Best regards,
[Rising Tech Open Source Software]
