### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by aneeshsvha** [RisingOSS-devices/official#17]
## Device you want to apply for
```Redmi 6 pro
Your device name and codename
```Redmi 6 pro (Sakura)

## Email address
```aneeshrt2019@gmail.com

## Device tree sources
<!--
* Must be public on GitHub/GitLab
* Must add kernel and vendor as well
* Authorship & commit history should be proper
* Add common trees if applicable
-->
```
https://github.com/aneeshsvha/android_device_xiaomi_daisy
https://github.com/aneeshsvha/android_device_xiaomi_msm8953-common

https://gitlab.com/itsvixano-dev/proprietary_vendor_xiaomi_daisy
https://gitlab.com/itsvixano-dev/proprietary_vendor_xiaomi_msm8953-common

https://github.com/xiaomi-msm8953-devs/android_kernel_xiaomi_msm8953
```

## Link to the platform where you have released your unofficial build
```
https://t.me/Redmi6ProNews/1632
```

## Other ROM's you maintain officially or unofficially
```
DroidX-UI
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
5 Months
```

## SELinux status?
```
Enforcing
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

## Contact
### Telegram username
```
obito_svha
```

**Comment by manidweep** [comment]
Hello,

Thank you for your interest in becoming a maintainer for RisingOS. Your application is currently marked as "Needs Resolution" or "Improvements" due to a critical issue on your side that must be addressed before our team can proceed with a full review.

🛠️ Please take the necessary steps to resolve the critical issue outlined in your application. Once resolved, our team will resume the review process.

⚠️ To keep up with your maintainership updates, please keep this issue open. In case of a change of mind, feel free to close this issue; however, inactivity will also result in this issue being closed.

🤖 Notice: This message is auto-generated. For any questions or assistance, please contact us at [[risingtechossofficial@gmail.com](mailto:risingtechossofficial@gmail.com)].

Best regards,
[Lord Itachi, Handler]
[Rising Tech Open Source Software]
